### ISSUE TITLE
@Ignore is not working

### ISSUE THREAD

**Issue by hyyan** [BBj-Plugins/BBjUnitTest#14]
marking a method with `@Ignore` does not show the ignored method in the test result and it does not appear with the Skipped filter

**Comment by SebastianAdams** [comment]
Do you have a sample for it ? 

BTW - You need to use it in addition to the **@Test** annotation like this:

```
rem @Ignore
rem @Test
method public void myTest()
...
```

**Comment by hyyan** [comment]
Oops, my fault, the `@Test` did the trick.
Thanks for help :)
